begin;

alter table if exists refined_submissions rename to refined_submissions_backup;

create table refined_submissions (
  id bigint generated by default as identity primary key,
  submission_id bigint not null unique references submissions(id) on delete cascade,
  semester integer not null check (semester between 1 and 8),
  course_code text not null default '',
  course_title text not null,
  program text not null,
  lecture_hours integer not null default 0,
  tutorial_hours integer not null default 0,
  practical_hours integer not null default 0,
  self_study integer not null default 0,
  credits integer not null default 0,
  course_type text not null,
  tools_languages text not null default '',
  desirable_knowledge text not null default '',
  prelude text not null default '',
  objectives text[] not null default '{}',
  course_outcomes text[] not null default '{}',
  units jsonb not null default '[]'::jsonb,
  lab_experiments text[] not null default '{}',
  text_books text[] not null default '{}',
  reference_books text[] not null default '{}',
  status text not null default 'refined',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(units) = 'array')
);

create index refined_submissions_semester_idx on refined_submissions (semester);

create or replace function set_refined_submissions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger refined_submissions_updated_at
before update on refined_submissions
for each row
execute function set_refined_submissions_updated_at();

insert into refined_submissions (
  id,
  submission_id,
  semester,
  course_code,
  course_title,
  program,
  lecture_hours,
  tutorial_hours,
  practical_hours,
  self_study,
  credits,
  course_type,
  tools_languages,
  desirable_knowledge,
  prelude,
  objectives,
  course_outcomes,
  units,
  lab_experiments,
  text_books,
  reference_books,
  status,
  created_at
)
select
  old.id,
  old.submission_id,
  coalesce(old.semester, (old.refined_content::jsonb ->> 'semester')::integer),
  coalesce(old.refined_content::jsonb ->> 'course_code', ''),
  coalesce(old.course_title, old.refined_content::jsonb ->> 'course_title'),
  coalesce(old.refined_content::jsonb ->> 'program', ''),
  coalesce((old.refined_content::jsonb ->> 'lecture_hours')::integer, 0),
  coalesce((old.refined_content::jsonb ->> 'tutorial_hours')::integer, 0),
  coalesce((old.refined_content::jsonb ->> 'practical_hours')::integer, 0),
  coalesce((old.refined_content::jsonb ->> 'self_study')::integer, 0),
  coalesce((old.refined_content::jsonb ->> 'credits')::integer, 0),
  coalesce(old.refined_content::jsonb ->> 'course_type', ''),
  coalesce(old.refined_content::jsonb ->> 'tools_languages', ''),
  coalesce(nullif(old.refined_content::jsonb ->> 'desirable_knowledge', '-'), ''),
  coalesce(old.prelude, old.refined_content::jsonb ->> 'prelude', ''),
  coalesce(array(select jsonb_array_elements_text(old.refined_content::jsonb -> 'objectives')), '{}'),
  coalesce(array(select jsonb_array_elements_text(old.refined_content::jsonb -> 'course_outcomes')), '{}'),
  coalesce(old.refined_content::jsonb -> 'units', '[]'::jsonb),
  coalesce(array(select jsonb_array_elements_text(old.refined_content::jsonb -> 'lab_experiments')), '{}'),
  coalesce(array(select line from regexp_split_to_table(sub.text_books, E'\\n+') line where btrim(line) <> ''), '{}'),
  coalesce(array(select line from regexp_split_to_table(coalesce(sub.reference_books, ''), E'\\n+') line where btrim(line) <> ''), '{}'),
  'refined',
  now()
from refined_submissions_backup old
left join submissions sub on sub.id = old.submission_id;

select setval(pg_get_serial_sequence('refined_submissions', 'id'), coalesce(max(id), 1), true)
from refined_submissions;

commit;
